### ISSUE TITLE
Spotbugs not found.

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/mobile-forms#1]
Steps to reproduce. 
- Create New Project
- Import custom work manager from this https://github.com/Samagra-Development/mobile-forms
- Added custom work manager in dependencies
- Importing collect_app, then it's throwing an error 
`ERROR: Plugin with id 'com.github.spotbugs'`

**Comment by umangbholasamagra** [comment]
Please follow these steps carefully. 

1. Copy config folder from the project, Add it to your to be implemented project.
2. Import common, customworkmanager module
3. Import collect_app module
3. Sync and build your project. If there are errors. do following:

a) Keep target sdk of your project 28. Collect won't work for target >28.
b) For project's build.gradle
      1. Edit buildscript tag with following repository dependencies.
buildscript {
    ext.kotlin_version = '1.3.71'
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://jitpack.io' }
    }
     2. Add these to your project's build.gradle
	dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.jakewharton:butterknife-gradle-plugin:10.1.0'
        classpath 'com.google.gms:google-services:4.3.0'
       }

      allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/groups/public' }
        maven { url 'https://jitpack.io' }
        maven { url 'https://staging.dev.medicmobile.org/_couch/maven-repo' }
    }
}

	ext {
    leakyCanaryVersion = '1.5.4'
    daggerVersion = '2.16'
    rxLifecycleVersion = '2.2.1'
    workManagerVersion = "1.0.0-alpha10"
    okhttp3Version = '3.12.3'
	}


	plugins {
    id 'com.github.spotbugs' version '1.6.4'
	} //Add this under buildscript block. refer downloaded project for more clarity

configurations.all {
    transitive = true
}

For app's build.gradle

In your app's build. gradle add 

apply plugin: 'com.jakewharton.butterknife'

Check if Android config matches as this


android {
    compileSdkVersion 28

    defaultConfig {
        applicationId "com.samagra.myapplication"
        minSdkVersion 19 // you can select it as per your choice and target
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
        incremental true
    }
}



dependencies {
   
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation project(":commons")
    implementation project(":collect_app")
}

In your Application  class please call this on your onCreate() method

Collect.getInstance().init(this, getApplicationContext(), new FormManagmentModuleInitialisationListener() {
            @Override
            public void onSuccess() {
                Timber.d("Form Module has been initialised correctly");
            }

            @Override
            public void onFailure(String message) {
                }
        });
 

The project should build successfully if all these steps are followed.
