### ISSUE TITLE
Duplicate Classes 

### ISSUE THREAD

**Issue by keshavashta** [Samagra-Development/mobile-forms#2]
After adding Ancillaryscreens dependency, while running getting the following error:

 **AGPBI: {"kind":"error","text":"Program type already present: com.google.android.youtube.player.YouTubeApiServiceUtil","sources":[{}],"tool":"D8"}**
<img width="1139" alt="error" src="https://user-images.githubusercontent.com/1171666/82245608-e10f2e00-9960-11ea-841b-52c4cec40753.png">

**App: build.gradle file contents**
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'io.fabric'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.luezoid.vaw"
        minSdkVersion 19
        targetSdkVersion 29
        versionCode 9
        versionName "1.8"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    dataBinding {
        enabled = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        incremental true
    }
    configurations {
        implementation.exclude module: 'guava'
    }
}

dependencies {
    def lifecycle_version = "2.1.0"
    def room_version = "2.2.5"
    def work_version = "2.3.4"
    def retrofitVersion = '2.7.1'
    def rxJavaVersion = '2.1.1'
    def butterKnifeVersion = '10.2.1'
    def daggerVersion = '2.26'
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(path: ':customworkmanager')
    implementation project(path: ':commons')
    implementation project(path: ':collect_app')
    implementation project(path: ':ancillaryscreens')
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.2.0-alpha05'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    //    Google Play Services
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'com.google.android.gms:play-services-auth:18.0.0'
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.google.firebase:firebase-auth:19.3.0'
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    implementation 'net.alexandroid.utils:gps:1.6'
    implementation 'com.google.android.gms:play-services-auth:18.0.0'
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.14.1'
    implementation 'javax.inject:javax.inject:1@jar'
    implementation 'com.riyagayasen.android:easyaccordion:1.0.3'
    implementation 'com.github.florent37:expansionpanel:1.1.1'
    implementation 'org.apache.httpcomponents:httpclient-android:4.3.5'
    implementation 'pub.devrel:easypermissions:3.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'com.bogdwellers:pinchtozoom:0.1'
    implementation 'com.github.stfalcon:stfalcon-imageviewer:1.0.1'
    annotationProcessor 'androidx.lifecycle:lifecycle-compiler:2.2.0'
    implementation('com.google.api-client:google-api-client-android:1.22.0') {
        exclude group: 'org.apache.httpcomponents'
    }
    implementation('com.google.apis:google-api-services-youtube:v3-rev183-1.22.0') {
        exclude group: 'org.apache.httpcomponents'
    }
    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }
    implementation 'com.squareup.picasso:picasso:2.71828'

    implementation 'org.greenrobot:eventbus:3.1.1'

    //        Retrofit libraries
    implementation "com.squareup.retrofit2:retrofit:$retrofitVersion"
    implementation "com.squareup.retrofit2:converter-gson:$retrofitVersion"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofitVersion"
    implementation "com.squareup.retrofit2:converter-moshi:$retrofitVersion"

    //        RxJava libraries
    implementation "io.reactivex.rxjava2:rxandroid:$rxJavaVersion"
    implementation "io.reactivex.rxjava2:rxjava:$rxJavaVersion"

    //        Butterknife libraries
    implementation "com.jakewharton:butterknife:$butterKnifeVersion"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    annotationProcessor "com.jakewharton:butterknife-compiler:$butterKnifeVersion"

    //        Dagger libraries
    implementation "com.google.dagger:dagger:$daggerVersion"
    annotationProcessor "com.google.dagger:dagger-compiler:$daggerVersion"
    implementation "com.google.dagger:dagger-android-support:$daggerVersion"
    annotationProcessor "com.google.dagger:dagger-android-processor:$daggerVersion"

    // ViewModel and LiveData
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.2.0'

    // Rx-Retrofit Call Adapter
    def rxcalladapter_version = '2.5.0'
    implementation "com.squareup.retrofit2:adapter-rxjava2:$rxcalladapter_version"
    // Retrofit call adapter

    // Reactive Streams (convert Observable to LiveData)
    def reactivestreams_version = "1.1.1"
    implementation 'androidx.lifecycle:lifecycle-reactivestreams:2.2.0'

    //        Firebase
    implementation 'com.google.firebase:firebase-auth:19.3.0'
    implementation 'com.google.firebase:firebase-core:17.3.0'
    implementation 'com.google.firebase:firebase-messaging:20.1.5'
    implementation 'com.google.firebase:firebase-analytics:17.3.0'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
    implementation 'com.google.firebase:firebase-messaging:20.1.5'
    implementation 'com.airbnb.android:lottie:3.0.7'
    implementation 'androidx.multidex:multidex:2.0.0'

    implementation('org.apache.httpcomponents:httpmime:4.5.6') {

        implementation group: 'org.apache.httpcomponents', name: 'httpclient-android', version: '4.3.5'
        implementation(group: 'org.apache.httpcomponents', name: 'httpmime', version: '4.3.5') {
            exclude module: 'org.apache.httpcomponents:httpclient'
        }

        configurations {
            all*.exclude group: 'commons-logging', module: 'commons-logging'
        }

        configurations {
            all*.exclude group: 'org.apache.httpcomponents', module: 'httpclient'
        }

        configurations {
            all*.exclude group: 'org.apache.commons', module: 'codec'
        }

        configurations {
            all*.exclude group: 'com.google.guava', module: 'listenablefuture'
        }
    }
    implementation('com.google.apis:google-api-services-youtube:v3-rev204-1.23.0') {
        exclude group: 'com.google.guava'
    }

    android {
        useLibrary 'org.apache.http.legacy'
    }
    implementation files('libs/YouTubeAndroidPlayerApi.jar')
    debugImplementation 'com.amitshekhar.android:debug-db:1.0.6'
    implementation "androidx.core:core-ktx:+"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

}
repositories {
    mavenCentral()
}

**Project build.gradle file content:**

buildscript {
    ext.kotlin_version = '1.3.71'
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        /*classpath 'org.ow2.asm:asm:6.2' // https://github.com/jacoco/jacoco/issues/639#issuecomment-355424756
        classpath 'org.jacoco:org.jacoco.core:0.8.0'
        classpath 'io.fabric.tools:gradle:1.28.1'*/
        /*classpath 'io.fabric.tools:gradle:1.28.1'*/
        classpath 'io.fabric.tools:gradle:1.31.2'
        classpath 'com.google.gms:google-services:4.3.0'
        classpath 'com.jakewharton:butterknife-gradle-plugin:10.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
plugins {
    id 'com.github.spotbugs' version '1.6.4'
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://oss.sonatype.org/content/groups/public' }
        maven { url 'https://jitpack.io' }
        maven { url 'https://staging.dev.medicmobile.org/_couch/maven-repo' }
    }
}

configurations.all {
    transitive = true
}

task checkAll(type: GradleBuild) {
    tasks = ['checkCode', 'checkTests']
}

task checkCode(type: GradleBuild) {
    tasks = ['pmd', 'checkstyle', 'lintDebug', 'spotbugs']
}

task checkTests(type: GradleBuild) {
    tasks = ['testDebugUnitTest', 'connectedDebugAndroidTest']
}

ext {
    leakyCanaryVersion = '1.5.4'
    daggerVersion = '2.16'
    rxLifecycleVersion = '2.2.1'
    workManagerVersion = "1.0.0-alpha10"
    okhttp3Version = '3.12.0'
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by ChakshuGautam** [comment]
Hey @keshavashta @umangbholasamagra is this resolved?

**Comment by keshavashta** [comment]
> Hey @keshavashta @umangbholasamagra is this resolved?

Yes, after removing ancillary screen module and code necessary files in our base project
